#ifndef INTERFACE_H
#define INTERFACE_H

#include <libxml2/libxml/parser.h>

#include "synth.h"

/* Render the ADSR envelope sliders */
void render_adsr(
    float *attack, float *decay, 
    float *sustain, float *release);

/* Render the filter ADSR envelope sliders */
void render_filter_adsr(synth_t *synth);

/* Render the filter ADSR envelope sliders */
void render_filter_adsr(synth_t *synth);

/* Render the oscillators waveforms dropdown menus*/
void render_osc_waveforms(
    int *wave_a, int *wave_b, int *wave_c, 
    bool *ddm_a, bool *ddm_b, bool *ddm_c);

/* Render the synthesizer parameters */
void render_synth_params(synth_t *synth);

/* Render the options menu */
void render_options(
    char *audio_filename,
    bool *saving_preset, bool *loading_preset,
    bool *saving_audio_file, bool *recording);

/* Render the effects parameters */
void render_effects(
    synth_t *synth, 
    bool *lfo_wave_ddm, bool *lfo_params_ddm,
    bool *distortion, bool *overdrive,
    float *distortion_amount);

/* Renders the waveform generated by the render_synth function */
void render_waveform(short *buffer);

/* Render the white keys from the MIDI piano visualizer */
void render_white_keys();

/* Render the black keys from the MIDI piano visualizer */
void render_black_keys();

/* Renders given note into a pressed key in the MIDI piano visualizer */
void render_key(int midi_note);

/* Outputs a given MIDI note rectangle parameters (x, y, width and height) */
void get_key_position(int midi_note, int *x, int *y,
                      int *width, int *height, int *is_black);

/* Returns if a MIDI note is a assigned to a black key or not */
int is_black_key(int midi_note);

#endif