#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <stdio.h>
#include <dirent.h>

#include <libxml2/libxml/parser.h>
#include <libxml2/libxml/tree.h>

#include "interface.h"
#include "synth.h"
#include "xml.h"


/*
 * Renders the global informations and menus about the synthesizer :
 * - ADSR envelope sliders
 * - Filter ADSR envelope sliders
 * - Oscillator waveforms dropdown menus
 * - Filter cutoff and filter envelope ON/OFF
 * - Amplification and detune effect
 */
void 
render_informations(
    synth_t *synth,
    float *attack, float *decay,
    float *sustain, float *release,
    int *wave_a, int *wave_b, int *wave_c,
    bool *ddm_a, bool *ddm_b, bool *ddm_c,
    char *preset_filename, bool *saving_preset)
{
    /* ADSR envelope sliders */
    GuiGroupBox((Rectangle){ 30, 30, WIDTH / 2 - 50, 160 }, "ADSR Envelope");
    /* Attack */
    GuiLabel((Rectangle){ 155, 40, 100, 20}, "Attack");
    GuiSlider((Rectangle){ 60, 60, 225, 40 }, NULL, NULL, 
            attack, 0.0f, 2.0f);
    /* Decay */
    GuiLabel((Rectangle){ 155, 110, 100, 20}, "Decay");
    GuiSlider((Rectangle){ 60, 130, 225, 40 }, NULL, NULL, 
            decay, 0.0f, 2.0f);
    /* Sustain */
    GuiLabel((Rectangle){ 415, 40, 100, 20}, "Sustain");
    GuiSlider((Rectangle){ 320, 60, 225, 40 }, NULL, NULL,
            sustain, 0.0f, 1.0f);
    /* Release */
    GuiLabel((Rectangle){ 415, 110, 100, 20}, "Release");
    GuiSlider((Rectangle){ 320, 130, 225, 40 }, NULL, NULL, 
            release, 0.0f, 1.0f);

    /* Filter ADSR envelope sliders */
    GuiGroupBox((Rectangle){ 625, 30, WIDTH / 2 - 50, 160 }, "Filter ADSR Envelope");
    /* Attack */
    GuiLabel((Rectangle){ 750, 40, 100, 20}, "Attack");
    GuiSlider((Rectangle){ 655, 60, 225, 40 }, NULL, NULL, 
            synth->filter->adsr->attack, 0.0f, 2.0f);
    /* Decay */
    GuiLabel((Rectangle){ 750, 110, 100, 20}, "Decay");
    GuiSlider((Rectangle){ 655, 130, 225, 40 }, NULL, NULL, 
            synth->filter->adsr->decay, 0.0f, 2.0f);
    /* Sustain */
    GuiLabel((Rectangle){ 1010, 40, 100, 20}, "Sustain");
    GuiSlider((Rectangle){ 915, 60, 225, 40 }, NULL, NULL, 
            synth->filter->adsr->sustain, 0.0f, 1.0f);
    /* Release */
    GuiLabel((Rectangle){ 1010, 110, 100, 20}, "Release");
    GuiSlider((Rectangle){ 915, 130, 225, 40 }, NULL, NULL, 
            synth->filter->adsr->release, 0.0f, 1.0f);

    /* Oscillators waveforms */
    GuiGroupBox((Rectangle){ 30, 220, WIDTH / 2 - 50, 160 }, "Oscillators");
    /* Oscillator A */
    GuiLabel((Rectangle){80, 255, 110, 20}, "Oscillator A");
    if (GuiDropdownBox((Rectangle){60, 275, 140, 40 }, 
        "#01#Sine wave;#02#Square wave;#03#Triangle wave;#04#Sawtooth wave", 
        wave_a, *ddm_a))
            *ddm_a = !*ddm_a;
    /* Oscillator B */
    GuiLabel((Rectangle){250, 255, 110, 20}, "Oscillator B");
    if (GuiDropdownBox((Rectangle){230, 275, 140, 40 }, 
        "#01#Sine wave;#02#Square wave;#03#Triangle wave;#04#Sawtooth wave", 
        wave_b, *ddm_b))
            *ddm_b = !*ddm_b;
    /* Oscillator C */
    GuiLabel((Rectangle){420, 255, 110, 20}, "Oscillator C");
    if (GuiDropdownBox((Rectangle){400, 275, 140, 40 }, 
        "#01#Sine wave;#02#Square wave;#03#Triangle wave;#04#Sawtooth wave", 
        wave_c, *ddm_c))
            *ddm_c = !*ddm_c;
    
    /* Synth parameters */
    GuiGroupBox((Rectangle){ 625, 220, WIDTH / 2 - 50, 160 }, "Synth parameters");
    /* Filter cutoff */
    GuiLabel((Rectangle){ 695, 230, 100, 20}, "Cutoff");
    GuiSlider((Rectangle){ 645, 250, 170, 40 }, NULL, NULL, 
            &synth->filter->cutoff, 0.0f, 1.0f);
    /* Synth detune effect */
    GuiLabel((Rectangle){ 695, 300, 100, 20}, "Detune");
    GuiSlider((Rectangle){ 645, 320, 170, 40 }, NULL, NULL, 
            &synth->detune, 0.0f, 1.0f);
    /* Amplification */
    GuiLabel((Rectangle){ 955, 230, 100, 20}, "Amp");
    GuiSlider((Rectangle){ 840, 250, 170, 40 }, NULL, NULL, 
            &synth->amp, 0.0f, 1.0f);
    /* Filter ADSR ON/OFF */
    GuiCheckBox((Rectangle){840, 320, 40, 40}, "Filter ADSR", 
            &synth->filter->env);

    /* Saving preset */
    if (GuiButton((Rectangle){ 1030, 250, 100, 40 }, "Save preset"))
        *saving_preset = true;

    if (*saving_preset)
        save_preset(
            synth, 
            attack, decay, sustain, release,
            wave_a, wave_b, wave_c,
            preset_filename, saving_preset);
            
    /* Loading preset */
    if (GuiButton((Rectangle){ 1030, 320, 100, 40 }, "Load preset"))
        load_preset(
            synth, 
            attack, decay, sustain, release,
            wave_a, wave_b, wave_c);
}


/* Renders the waveform generated by the render_synth function */
void 
render_waveform(short *buffer)
{
    GuiGroupBox((Rectangle){ 30, 410, WIDTH - 55, 160}, "Waveform");

    int mid_y = HEIGHT / 4 + 25;
    int y = HEIGHT / 3 + mid_y;

    int step = 1;

    for (int i = 13; i < FRAMES - 11; i += step)
    {
        int x1 = (i * WIDTH) / FRAMES;
        int x2 = ((i + step) * WIDTH) / FRAMES;

        int y1 = y - ((buffer[i] * mid_y) / 32768);
        int y2 = y - ((buffer[i + step] * mid_y) / 32768);

        /* Preventing going past the GuiGroupBox */
        if (y1 < 410) y1 = 410;
        if (y2 < 410) y2 = 410;
        if (y1 > 570) y1 = 570;
        if (y2 > 570) y2 = 570;

        DrawLine(x1, y1, x2, y2, BLACK);
    }
}

/* Render the white keys from the MIDI piano visualizer */
void 
render_white_keys()
{
    for (int i = 0; i < WHITE_KEYS; i++)
    {
        DrawRectangleLines(i * WHITE_KEYS_WIDTH, HEIGHT - WHITE_KEYS_HEIGHT, 
            WHITE_KEYS_WIDTH + 1, WHITE_KEYS_HEIGHT, BLACK);   
    }
}

/* Render the black keys from the MIDI piano visualizer */
void 
render_black_keys()
{
    char black_keys_pattern[] = {1, 1, 0, 1, 1, 1, 0, 0};
    int white_key_index = 0;
    for (int octave = 0; octave <= (WHITE_KEYS / 7); octave++)
    {
        for (int i = 0; i < 7; i++)
        {
            if (black_keys_pattern[i])
            {
                int x = (white_key_index * WHITE_KEYS_WIDTH) + WHITE_KEYS_WIDTH - (BLACK_KEYS_WIDTH / 2);
                DrawRectangle(x, HEIGHT - WHITE_KEYS_HEIGHT,
                                BLACK_KEYS_WIDTH, BLACK_KEYS_HEIGHT, BLACK);
            }
            white_key_index++;
            if (white_key_index >= WHITE_KEYS)
                break;
        }
        if (white_key_index >= WHITE_KEYS)
            break;
    }
}

/* Renders given note into a pressed key in the MIDI piano visualizer */
void 
render_key(int midi_note)
{
    int width = 0, height = 0, x = 0, y = 0, is_black = 0;
    get_key_position(midi_note, &x, &y, &width, &height, &is_black);

    DrawRectangle(x, y, width, height, (Color){151, 232, 255, 255});
    DrawRectangleLines(x, y, width, height, BLACK);
    /* Avoid double thick line when pressing a white key */
    if (!is_black) DrawLine(x + width, y, x + width, y + height - 1, (Color){151, 232, 255, 255});
}

/* Outputs a given MIDI note rectangle parameters (x, y, width and height) */
void 
get_key_position(int midi_note, int *x, int *y, 
                int *width, int *height, int *is_black)
{
    int note_in_octave = midi_note % 12;
    int octave = midi_note / 12;

    static const int black_keys[] = {0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0};
    *is_black = black_keys[note_in_octave];

    static const int white_key_map[] = {0, 0, 1, 1, 2, 3, 3, 4, 4, 5, 5, 6};
    int white_key_in_octave = white_key_map[note_in_octave];

    int white_key_index = (octave * 7) + white_key_in_octave;

    if (*is_black)
    {
        *width = WHITE_KEYS_WIDTH / 2;
        *height = (WHITE_KEYS_HEIGHT * 2) / 3;
        *x = (white_key_index * WHITE_KEYS_WIDTH) + WHITE_KEYS_WIDTH - (*width / 2);
        *y = HEIGHT - WHITE_KEYS_HEIGHT;
    }
    else
    {
        *width = WHITE_KEYS_WIDTH;
        *height = WHITE_KEYS_HEIGHT;
        *x = white_key_index * WHITE_KEYS_WIDTH;
        *y = HEIGHT - WHITE_KEYS_HEIGHT;
    }
}

/* Returns if a MIDI note is a assigned to a black key or not */
int 
is_black_key(int midi_note)
{
    int note = midi_note % 12;
    return (note == 1 || note == 3 || note == 6 || note == 8 || note == 10);
}